version: '3'
services:
  server:
    image: redash/redash:7.0.0.b18042
    depends_on:
      - postgres
      - redis
      - clickhouse
    # volumes:
    #   - /home/jorge/Projects/Personal/DataVisualization/redash-data:/app
    env_file: /home/jorge/Projects/Personal/DataVisualization/env
    restart: always
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    image: redash/redash:7.0.0.b18042
    depends_on:
      - server
    env_file: /home/jorge/Projects/Personal/DataVisualization/env
    restart: always
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    image: redash/redash:7.0.0.b18042
    depends_on:
      - server
    env_file: /home/jorge/Projects/Personal/DataVisualization/env
    restart: always
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    image: redash/redash:7.0.0.b18042
    depends_on:
      - server
    env_file: /home/jorge/Projects/Personal/DataVisualization/env
    restart: always
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0.4-alpine
  postgres:
    image: postgres:11.2-alpine
    env_file: /home/jorge/Projects/Personal/DataVisualization/env
    volumes:
      - /home/jorge/Projects/Personal/DataVisualization/postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
  clickhouse:
    image: yandex/clickhouse-server:19.4.3.11
    volumes:
      - /home/jorge/Projects/Personal/DataVisualization/clickhouse-data:/var/lib/clickhouse
    ports:
     - "8123:8123"
